bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: mu1Nj+QwxMvyE+Wj6VAIf+0l3ufZzLJgdyeEXviq1Ln2ruZvWhjkWiKpktLi6W+PUwiJALh1ljRT3lkZkBFCdz7EFYh+XqsrK5DOwmxRIHGQ8bGZqPKywEYMK8/w7fp10eDxVvBgwrGiXiZeXXF2MipaBgppajalY6L5zTIh8xP3eA+Oi4/2Kurf6vuvsX3oNWjkvdqI0QgRwWvi5I4/n18UMO6ihLVpRxxVDB4/qt0+nRFVbgk5Fy3EDfQSMHyp+j/M1cejJwPhVmVH94pQ9ANbf/2IgtUJD3i9XeAHinvTHQ/CEjCP14w7C2aMnq0C2Oi10EpzSVU41J4T+gLvzYAkQsQrK8OvTTl0ZvS5ZBWF1RNfWsX2cYklvT6/hcllmYY6gjvj4QOqmzbNDv30L0MZzYU9wTfSqPgYBAnQGMBCsFTqsLKtStfakvWc76MYj6cZ81eotVEGmhhrp1bERwQw/zoYS3HdsTE8fmATzAbQYb5HrqESYfXc5rkOqe/qc4AlZ8Ej+KbmgmAZBbCVGruBOIV271cmOFxPabjAOz6Fjjv6YqPhIpiQgb3Ebjl76NgHqmVE9aOodbluhV7x6hQMQIVJPhpFFs9XiNHJAPXA5fLaSD98CKr2jtm51OMQrne+NDD6ae3eGFjAK3Y9s7NOBqsUAyuCEAaNbbW6mrE=
conda_forge_output_validation: true
